#!/bin/bash

# Ask some questions and collect the answer

dialog --title "Questionnaire" --msgbox "Welcome to my simple survey" 9 18

dialog --title "Confirm" --yesno "Are you willing to take part?" 9 18
if [ $? != 0]; then
    dialog --infobox "Thank you anyway" 5 20
    sleep 2
    dialog --clear
    exit 0
fi

# Ask the user his name and redirect the standard error stream, 2, into a temporary file
dialog --title "Questionnaire" --inputbox "Plase enter your name" 9 30 2>_1.txt
Q_NAME=$(cat _1.txt)

# Menu item with four different options
dialog --menu "$Q_NAME, what music do you like best?" 15 30 4 1 "Classical" 2 "Jazz" 3 "Country" 4 "Other" 2>_1.txt
Q_MUSIC=$(cat _1.txt)

# Test the result
if [ "$Q_MUSIC" = "1" ]; then
    dialog --title "Likes Classical" --msgbox "Good choice!" 12 25
else
    dialog --title "Doesn't like Classical" --msgbox "Shame" 12 25
fi

# Clear the last dialog box and exit the program
sleep 2
dialog --clear
exit 0

