CC = gcc
CFLAGS = -Wall -g
RM = rm -f

.PHONY: all clean

all: computer_dating

computer_dating: computer_dating.c
	$(CC) $(CFLAGS) -o computer_dating computer_dating.c

clean:
	$(RM) computer_dating
